
package com.iris.test.webservice.cxpt;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2016-06-14T11:33:47.790+08:00
 * Generated source version: 3.1.1
 * 
 */
 
public class ICdxyWebserviceActionPortType_ICdxyWebserviceActionPort_Server{

    protected ICdxyWebserviceActionPortType_ICdxyWebserviceActionPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ICdxyWebserviceActionPortImpl();
        String address = "http://118.122.92.102:7712/newCdxyWebservice/services/cdxyservice";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ICdxyWebserviceActionPortType_ICdxyWebserviceActionPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
