package com.iris.test.webservice.cxpt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2016-06-14T11:33:47.784+08:00
 * Generated source version: 3.1.1
 * 
 */
@WebService(targetNamespace = "http://web.webservice.dt.com/", name = "ICdxyWebserviceActionPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ICdxyWebserviceActionPortType {

    @WebResult(name = "return", targetNamespace = "http://web.webservice.dt.com/")
    @RequestWrapper(localName = "queryQyDetail", targetNamespace = "http://web.webservice.dt.com/", className = "com.iris.test.webservice.cxpt.QueryQyDetail")
    @WebMethod
    @ResponseWrapper(localName = "queryQyDetailResponse", targetNamespace = "http://web.webservice.dt.com/", className = "com.iris.test.webservice.cxpt.QueryQyDetailResponse")
    public java.lang.String queryQyDetail(
        @WebParam(name = "arg0", targetNamespace = "http://web.webservice.dt.com/")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "http://web.webservice.dt.com/")
    @RequestWrapper(localName = "getBlxxList", targetNamespace = "http://web.webservice.dt.com/", className = "com.iris.test.webservice.cxpt.GetBlxxList")
    @WebMethod
    @ResponseWrapper(localName = "getBlxxListResponse", targetNamespace = "http://web.webservice.dt.com/", className = "com.iris.test.webservice.cxpt.GetBlxxListResponse")
    public java.lang.String getBlxxList(
        @WebParam(name = "arg0", targetNamespace = "http://web.webservice.dt.com/")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "http://web.webservice.dt.com/")
    @RequestWrapper(localName = "getQyList", targetNamespace = "http://web.webservice.dt.com/", className = "com.iris.test.webservice.cxpt.GetQyList")
    @WebMethod
    @ResponseWrapper(localName = "getQyListResponse", targetNamespace = "http://web.webservice.dt.com/", className = "com.iris.test.webservice.cxpt.GetQyListResponse")
    public java.lang.String getQyList(
        @WebParam(name = "arg0", targetNamespace = "http://web.webservice.dt.com/")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "http://web.webservice.dt.com/")
    @RequestWrapper(localName = "getQyDetail", targetNamespace = "http://web.webservice.dt.com/", className = "com.iris.test.webservice.cxpt.GetQyDetail")
    @WebMethod
    @ResponseWrapper(localName = "getQyDetailResponse", targetNamespace = "http://web.webservice.dt.com/", className = "com.iris.test.webservice.cxpt.GetQyDetailResponse")
    public java.lang.String getQyDetail(
        @WebParam(name = "arg0", targetNamespace = "http://web.webservice.dt.com/")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "http://web.webservice.dt.com/")
    @RequestWrapper(localName = "getRyxxList", targetNamespace = "http://web.webservice.dt.com/", className = "com.iris.test.webservice.cxpt.GetRyxxList")
    @WebMethod
    @ResponseWrapper(localName = "getRyxxListResponse", targetNamespace = "http://web.webservice.dt.com/", className = "com.iris.test.webservice.cxpt.GetRyxxListResponse")
    public java.lang.String getRyxxList(
        @WebParam(name = "arg0", targetNamespace = "http://web.webservice.dt.com/")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "http://web.webservice.dt.com/")
    @RequestWrapper(localName = "getXzxkList", targetNamespace = "http://web.webservice.dt.com/", className = "com.iris.test.webservice.cxpt.GetXzxkList")
    @WebMethod
    @ResponseWrapper(localName = "getXzxkListResponse", targetNamespace = "http://web.webservice.dt.com/", className = "com.iris.test.webservice.cxpt.GetXzxkListResponse")
    public java.lang.String getXzxkList(
        @WebParam(name = "arg0", targetNamespace = "http://web.webservice.dt.com/")
        java.lang.String arg0
    );
}
