
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.iris.test.webservice.cxpt;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2016-06-14T11:33:47.773+08:00
 * Generated source version: 3.1.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "ICdxyWebserviceAction",
                      portName = "ICdxyWebserviceActionPort",
                      targetNamespace = "http://web.webservice.dt.com/",
                      wsdlLocation = "http://118.122.92.102:7712/newCdxyWebservice/services/cdxyservice?wsdl",
                      endpointInterface = "com.iris.test.webservice.cxpt.ICdxyWebserviceActionPortType")
                      
public class ICdxyWebserviceActionPortImpl implements ICdxyWebserviceActionPortType {

    private static final Logger LOG = Logger.getLogger(ICdxyWebserviceActionPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.iris.test.webservice.cxpt.ICdxyWebserviceActionPortType#queryQyDetail(java.lang.String  arg0 )*
     */
    public java.lang.String queryQyDetail(java.lang.String arg0) { 
        LOG.info("Executing operation queryQyDetail");
        System.out.println(arg0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.iris.test.webservice.cxpt.ICdxyWebserviceActionPortType#getBlxxList(java.lang.String  arg0 )*
     */
    public java.lang.String getBlxxList(java.lang.String arg0) { 
        LOG.info("Executing operation getBlxxList");
        System.out.println(arg0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.iris.test.webservice.cxpt.ICdxyWebserviceActionPortType#getQyList(java.lang.String  arg0 )*
     */
    public java.lang.String getQyList(java.lang.String arg0) { 
        LOG.info("Executing operation getQyList");
        System.out.println(arg0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.iris.test.webservice.cxpt.ICdxyWebserviceActionPortType#getQyDetail(java.lang.String  arg0 )*
     */
    public java.lang.String getQyDetail(java.lang.String arg0) { 
        LOG.info("Executing operation getQyDetail");
        System.out.println(arg0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.iris.test.webservice.cxpt.ICdxyWebserviceActionPortType#getRyxxList(java.lang.String  arg0 )*
     */
    public java.lang.String getRyxxList(java.lang.String arg0) { 
        LOG.info("Executing operation getRyxxList");
        System.out.println(arg0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.iris.test.webservice.cxpt.ICdxyWebserviceActionPortType#getXzxkList(java.lang.String  arg0 )*
     */
    public java.lang.String getXzxkList(java.lang.String arg0) { 
        LOG.info("Executing operation getXzxkList");
        System.out.println(arg0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
