package com.iris.test.webservice.cxpt;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2016-06-14T11:33:47.807+08:00
 * Generated source version: 3.1.1
 * 
 */
@WebServiceClient(name = "ICdxyWebserviceAction", 
                  wsdlLocation = "http://118.122.92.102:7712/newCdxyWebservice/services/cdxyservice?wsdl",
                  targetNamespace = "http://web.webservice.dt.com/") 
public class ICdxyWebserviceAction extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://web.webservice.dt.com/", "ICdxyWebserviceAction");
    public final static QName ICdxyWebserviceActionPort = new QName("http://web.webservice.dt.com/", "ICdxyWebserviceActionPort");
    static {
        URL url = null;
        try {
            url = new URL("http://118.122.92.102:7712/newCdxyWebservice/services/cdxyservice?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ICdxyWebserviceAction.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://118.122.92.102:7712/newCdxyWebservice/services/cdxyservice?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ICdxyWebserviceAction(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ICdxyWebserviceAction(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ICdxyWebserviceAction() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ICdxyWebserviceAction(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ICdxyWebserviceAction(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ICdxyWebserviceAction(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ICdxyWebserviceActionPortType
     */
    @WebEndpoint(name = "ICdxyWebserviceActionPort")
    public ICdxyWebserviceActionPortType getICdxyWebserviceActionPort() {
        return super.getPort(ICdxyWebserviceActionPort, ICdxyWebserviceActionPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICdxyWebserviceActionPortType
     */
    @WebEndpoint(name = "ICdxyWebserviceActionPort")
    public ICdxyWebserviceActionPortType getICdxyWebserviceActionPort(WebServiceFeature... features) {
        return super.getPort(ICdxyWebserviceActionPort, ICdxyWebserviceActionPortType.class, features);
    }

}
