package com.iris.test.webservice.idcard.com._36wu;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-07-11T09:39:20.625+08:00
 * Generated source version: 3.1.1
 * 
 */
@WebService(targetNamespace = "http://www.36wu.com/", name = "IdCardServiceHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IdCardServiceHttpPost {

    /**
     * <h3>身份证查询</h3>
     */
    @WebResult(name = "ResultOfIdCard", targetNamespace = "http://www.36wu.com/", partName = "Body")
    @WebMethod(operationName = "GetIdCardInfo")
    public ResultOfIdCard getIdCardInfo(
        @WebParam(partName = "idcard", name = "idcard", targetNamespace = "http://www.36wu.com/")
        java.lang.String idcard,
        @WebParam(partName = "authkey", name = "authkey", targetNamespace = "http://www.36wu.com/")
        java.lang.String authkey
    );
}
