package com.iris.test.webservice.idcard.com._36wu;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-07-11T09:39:20.529+08:00
 * Generated source version: 3.1.1
 * 
 */
@WebService(targetNamespace = "http://www.36wu.com/", name = "IdCardServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface IdCardServiceSoap {

    /**
     * <h3>身份证查询</h3>
     */
    @WebResult(name = "GetIdCardInfoResult", targetNamespace = "http://www.36wu.com/")
    @RequestWrapper(localName = "GetIdCardInfo", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetIdCardInfo")
    @WebMethod(operationName = "GetIdCardInfo", action = "http://www.36wu.com/GetIdCardInfo")
    @ResponseWrapper(localName = "GetIdCardInfoResponse", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetIdCardInfoResponse")
    public com.iris.test.webservice.idcard.com._36wu.ResultOfIdCard getIdCardInfo(
        @WebParam(name = "idcard", targetNamespace = "http://www.36wu.com/")
        java.lang.String idcard,
        @WebParam(name = "authkey", targetNamespace = "http://www.36wu.com/")
        java.lang.String authkey
    );
}
